# Enable C++ support
sudo: required
dist: trusty
language: cpp
# Compiler selection
matrix:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev libboost-filesystem-dev
install:
  - sudo pip install -r requirements.txt
# Build steps
script:
  -echo $COMPILER
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make && make test
