# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev libboost-filesystem-dev
# Build steps
script:
  - cmake . && make
