# Enable C++ support
dist: trusty
language: cpp
# Compiler selection

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev libboost-filesystem-dev
# Build steps
script:
  - sudo pip install -r requirements.txt
  - cmake . && make && make test
